# Site Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed]

# Customise feed settings (uncommenting following two fields to customise feed title and description)
#title:		           "The Awakened Mind"
#description:	       "personal growth and development"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#   path:	     rss-feed.xml
