title:  The Awakened Mind
tagline:  personal growth and development

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'amindawakened'

google-ID: 'UA-80213386-1'

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Archives', url: 'archives.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/djmunro'}
- {icon: 'twitter', link: 'https://twitter.com/munrodj86'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/david-munro-12a573b7'}
- {icon: 'envelope', link: 'mailto:munrodj86@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
